global:
  scrape_interval:     5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'sampleapp'
    static_configs:
    - targets: ['host.docker.internal:8080']
